import { Report, Officer, AuditLog, SystemConfig, ReportStatus } from "./types";

export const INITIAL_SYSTEM_CONFIG: SystemConfig = {
  globalThreshold: 50,
  geofencingRadiusMeters: 500,
  autoEscalationEnabled: true,
};

export const INITIAL_OFFICERS: Officer[] = [
  {
    id: "off-1",
    name: "Ir. Bambang Wijaya, M.T.",
    nip: "19880412 201402 1 003",
    role: "super_admin",
    roleLabel: "Super Admin DLH",
    region: "Seluruh Jabodetabek",
    phone: "+62 812-3456-7890",
    email: "bambang.wijaya@dlh.jakarta.go.id",
    activeWorkload: 4,
    completedTasks: 142,
  },
  {
    id: "off-2",
    name: "Drs. Heru Prasetyo",
    nip: "19790315 200801 1 007",
    role: "korwil",
    roleLabel: "Koordinator Wilayah Jakarta Selatan",
    region: "Jakarta Selatan (Ciliwung Hilir)",
    phone: "+62 813-9876-5432",
    email: "heru.prasetyo@dlh.jakarta.go.id",
    activeWorkload: 6,
    completedTasks: 98,
  },
  {
    id: "off-3",
    name: "Suryadi Pasukan Oranye",
    nip: "19920721 201903 1 012",
    role: "petugas_lapangan",
    roleLabel: "Petugas Lapangan Pasukan Oranye",
    region: "Manggarai - Kampung Melayu",
    phone: "+62 857-1122-3344",
    email: "suryadi.lapangan@dlh.jakarta.go.id",
    activeWorkload: 2,
    completedTasks: 76,
  },
];

export const MOCK_REPORTS: Report[] = [
  {
    id: "rpt-101",
    ticketNo: "DLH-2026-0891",
    riverName: "Kali Ciliwung - Segmen Manggarai",
    region: "Jakarta Selatan",
    category: "limbah-cair",
    categoryLabel: "Limbah Cair Industri",
    locationDetail: "Dekat Pintu Air Manggarai RT 05/03",
    lat: -6.235,
    lng: 106.854,
    description: "Air sungai berubah warna menjadi keruh kehitaman dan mengeluarkan cairan berbusa pekat sejak pukul 07:00 WIB.",
    reporterName: "Budi Santoso",
    isAnonymous: false,
    upvotes: 64,
    voteThreshold: 50,
    urgencyScore: 142,
    status: "terverifikasi",
    createdAt: "2026-07-31T08:15:00Z",
    updatedAt: "2026-07-31T09:00:00Z",
    beforeImages: ["/assets/sungai/Pencemaran Teluk Jakarta oleh Paracetamol.jpg"],
    subReports: [
      {
        id: "sub-101-a",
        reporterName: "Dedi Susanto",
        category: "bau-warna",
        categoryLabel: "Bau Menyengat",
        description: "Bau menyengat tercium hingga radius 300m dari bantaran sungai.",
        images: ["/assets/sungai/Mengerikan! Ini Penampakan Pencemaran Sungai di Jakarta.jpeg"],
        createdAt: "2026-07-31T08:30:00Z",
        lat: -6.2352,
        lng: 106.8543,
      },
    ],
    timeline: [
      { status: "pending", label: "Laporan Dibuat Warga", timestamp: "2026-07-31 08:15", actor: "Budi Santoso" },
      { status: "terverifikasi", label: "Mencapai Threshold (Diteruskan ke DLH)", timestamp: "2026-07-31 09:00", actor: "Sistem Otomatis" },
    ],
  },
  {
    id: "rpt-102",
    ticketNo: "DLH-2026-0885",
    riverName: "Kali Cipinang - Segmen Jatinegara",
    region: "Jakarta Timur",
    category: "sampah",
    categoryLabel: "Tumpukan Sampah Plastik",
    locationDetail: "Bantaran sungai samping jembatan penyeberangan Jatinegara",
    lat: -6.229,
    lng: 106.876,
    description: "Penumpukan kantong sampah plastik rumah tangga dan kayu bekas yang menyumbat aliran air.",
    reporterName: "Siti Rahma",
    isAnonymous: false,
    upvotes: 95,
    voteThreshold: 50,
    urgencyScore: 210,
    status: "diproses",
    createdAt: "2026-07-31T07:30:00Z",
    updatedAt: "2026-07-31T10:15:00Z",
    assignedOfficerId: "off-3",
    assignedOfficerName: "Suryadi Pasukan Oranye",
    beforeImages: ["/assets/sungai/20200812-Sungai-Ciliwung-1_ratio-16x9.jpg"],
    subReports: [],
    timeline: [
      { status: "pending", label: "Laporan Dibuat Warga", timestamp: "2026-07-31 07:30", actor: "Siti Rahma" },
      { status: "terverifikasi", label: "Terverifikasi Warga", timestamp: "2026-07-31 08:45", actor: "Sistem Otomatis" },
      { status: "diproses", label: "Tim Lapangan Didispensasikan", timestamp: "2026-07-31 10:15", actor: "Drs. Heru Prasetyo" },
    ],
  },
  {
    id: "rpt-103",
    ticketNo: "DLH-2026-0870",
    riverName: "Kali Bekasi - Segmen Bendung Bekasi",
    region: "Kota Bekasi",
    category: "bau-warna",
    categoryLabel: "Busa & Air Berbau",
    locationDetail: "Hilir Bendung Bekasi Jalan Mayor Oking",
    lat: -6.23,
    lng: 107.002,
    description: "Tumpukan busa putih tebal membumbung di atas air sungai dan menimbulkan bau asam menyengat.",
    reporterName: "Ahmad Hidayat",
    isAnonymous: true,
    upvotes: 78,
    voteThreshold: 50,
    urgencyScore: 178,
    status: "terverifikasi",
    createdAt: "2026-07-31T06:45:00Z",
    updatedAt: "2026-07-31T08:00:00Z",
    beforeImages: ["/assets/sungai/Mengerikan! Ini Penampakan Pencemaran Sungai di Jakarta.jpeg"],
    subReports: [],
    timeline: [
      { status: "pending", label: "Laporan Dibuat Warga", timestamp: "2026-07-31 06:45", actor: "Warga Anonim" },
      { status: "terverifikasi", label: "Terverifikasi Threshold", timestamp: "2026-07-31 08:00", actor: "Sistem Otomatis" },
    ],
  },
  {
    id: "rpt-104",
    ticketNo: "DLH-2026-0842",
    riverName: "Kali Sunter - Segmen Kelapa Gading",
    region: "Jakarta Utara",
    category: "sampah",
    categoryLabel: "Penyumbatan Sampah Rumah Tangga",
    locationDetail: "Polder Danau Sunter Selatan",
    lat: -6.14,
    lng: 106.872,
    description: "Eceng gondok dan sampah botol plastik menutupi permukaan air polder.",
    reporterName: "Dewi Lestari",
    isAnonymous: false,
    upvotes: 42,
    voteThreshold: 50,
    urgencyScore: 95,
    status: "selesai",
    createdAt: "2026-07-30T10:00:00Z",
    updatedAt: "2026-07-30T16:30:00Z",
    assignedOfficerId: "off-3",
    assignedOfficerName: "Suryadi Pasukan Oranye",
    beforeImages: ["/assets/sungai/sungai ciliwung bening.jpg"],
    afterImage: "/assets/sungai/sungai ciliwung bening.jpg",
    officerNote: "Telah diangkut 3.2 ton sampah plastik menggunakan 2 unit truk sampah DLH. Air mengalir lancar.",
    subReports: [],
    timeline: [
      { status: "pending", label: "Laporan Dibuat Warga", timestamp: "2026-07-30 10:00", actor: "Dewi Lestari" },
      { status: "terverifikasi", label: "Terverifikasi Manual Korwil", timestamp: "2026-07-30 11:20", actor: "Ir. Bambang Wijaya" },
      { status: "diproses", label: "Pembersihan Lapangan", timestamp: "2026-07-30 13:00", actor: "Suryadi Pasukan Oranye" },
      { status: "selesai", label: "Closed-Loop Selesai Clean", timestamp: "2026-07-30 16:30", actor: "Suryadi Pasukan Oranye" },
    ],
  },
  {
    id: "rpt-105",
    ticketNo: "DLH-2026-0811",
    riverName: "Kali Pesanggrahan - Segmen Kebayoran",
    region: "Jakarta Selatan",
    category: "tanggul",
    categoryLabel: "Kerusakan Tanggul & Longsor",
    locationDetail: "Bantaran Kali Pesanggrahan RT 02/08",
    lat: -6.26,
    lng: 106.77,
    description: "Laporan tanah longsor akibat erosi debit air deras setelah hujan deras kemarin malam.",
    reporterName: "Rian Kurniawan",
    isAnonymous: false,
    upvotes: 12,
    voteThreshold: 50,
    urgencyScore: 28,
    status: "pending",
    createdAt: "2026-07-31T09:10:00Z",
    updatedAt: "2026-07-31T09:10:00Z",
    beforeImages: ["/assets/sungai/20200812-Sungai-Ciliwung-1_ratio-16x9.jpg"],
    subReports: [],
    timeline: [
      { status: "pending", label: "Laporan Dibuat (Mengumpulkan Vote)", timestamp: "2026-07-31 09:10", actor: "Rian Kurniawan" },
    ],
  },
];

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    id: "log-1",
    timestamp: "2026-07-31 10:15:04",
    ticketNo: "DLH-2026-0885",
    actorName: "Drs. Heru Prasetyo",
    actorRole: "Koordinator Wilayah",
    action: "Disposisi Tim Lapangan",
    details: "Menugaskan Suryadi Pasukan Oranye (Armada Truk 04) ke Kali Cipinang.",
  },
  {
    id: "log-2",
    timestamp: "2026-07-31 09:00:12",
    ticketNo: "DLH-2026-0891",
    actorName: "Sistem Spasial Auto",
    actorRole: "Automated System",
    action: "Eskalasi Threshold",
    details: "Vote mencapai 64/50 (+142 Urgency Score). Status otomatis menjadi Terverifikasi 🔴.",
  },
];
